main: ca.echau.myfirstplugin.Main
name: MyFirstPlugin
version: 1.0
author: Eugene Chau
description: MyFirstPlugin adds many features and commands that are not connected to one another.
commands:
  cointoss:
    description: Flip a coin! Guess either heads or tails and see what happens.
    usage: /cointoss <heads / tails>
  damage:
    description: Damages a player by the specified amount of hearts.
    usage: /damage <player> <number of hearts>
  enablefarts:
    description: Enables Farts Mode for the specified player. Sneak to fart!
    usage: /enablefarts [player]
    aliases: ef
  enablepooping:
    description: Enables the ability to poop for the specified player. Sneak to poop!
    usage: /enablepooping [player]
    aliases: ep
  exarrows:
    description: Toggles Explosive Arrows for the specified player. When enabled, arrows explode upon landing.
    usage: /exarrows [player]
  feed:
    description: Gives yourself/someone full hunger bars.
    usage: /feed [player]
  givedirt:
    description: Gives a player the specified amount of dirt.
    usage: /givedirt <player> [amount]
  heal:
    description: Gives yourself/someone full health.
    usage: /heal [player]
  launchmode:
    description: Toggles Launch Mode for the specified player. When enabled, shooting a bow will launch you in the air.
    usage: /launchmode [player]
    aliases: lm
  meme:
    description: Displays a random meme.
    usage: /meme
  modes:
    description: Returns a list of enabled MyFirstPlugin modes for the specified player.
    usage: /modes [player]
  orelogs:
    description: Views OreLogs of a specified player. OreLogs displays all ores that a player has mined in the past hour.
    usage: /orelogs <player>
  rainbowarmor:
    description: Toggles Rainbow Armor for the specified player. When enabled, equipped leather armor always changes color.
    usage: /rainbowarmor [player]
    aliases: rarmor
  rectanglearea:
    description: Calculates the area of a rectangle with the specified length and width.
    usage: /rectanglearea <length> <width>
    aliases: recarea
  reverse:
    description: Reverses the word(s) you put into the command.
    usage: /reverse <a string of words>
  rteleport:
    description: Teleports you to a random location.
    usage: /rteleport
    aliases: rtp
  setfartdmg:
    description: Sets the damage of a Fart (produced when sneaking in Farts Mode) to the specified number of hearts.
    usage: /setfartdmg <number of hearts>
  setspawn:
    description: Sets world spawn of the world you are currently in. 
    usage: /setspawn
  spawn:
    description: Teleports to the spawn of the world you are currently in.
    usage: /spawn
  tplightning:
    description: Teleports to a player and strikes them with lightning!
    usage: /tplightning <player>
    aliases: tpl
  walkonsmoke:
    description: Toggles WalkOnSmoke Mode for the specified player. When enabled, fly around in the air and look down at your feet!
    usage: /walkonsmoke [player]
    aliases: wos